# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import computation_pb2 as computation__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in computation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputationServiceStub(object):
    """计算服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitComputation = channel.unary_unary(
                '/eon.ComputationService/SubmitComputation',
                request_serializer=computation__pb2.ComputationRequest.SerializeToString,
                response_deserializer=computation__pb2.ComputationResponse.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/eon.ComputationService/GetTaskStatus',
                request_serializer=computation__pb2.TaskStatusRequest.SerializeToString,
                response_deserializer=computation__pb2.TaskStatusResponse.FromString,
                _registered_method=True)


class ComputationServiceServicer(object):
    """计算服务
    """

    def SubmitComputation(self, request, context):
        """提交计算任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """获取任务状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitComputation': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitComputation,
                    request_deserializer=computation__pb2.ComputationRequest.FromString,
                    response_serializer=computation__pb2.ComputationResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=computation__pb2.TaskStatusRequest.FromString,
                    response_serializer=computation__pb2.TaskStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eon.ComputationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eon.ComputationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputationService(object):
    """计算服务
    """

    @staticmethod
    def SubmitComputation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eon.ComputationService/SubmitComputation',
            computation__pb2.ComputationRequest.SerializeToString,
            computation__pb2.ComputationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eon.ComputationService/GetTaskStatus',
            computation__pb2.TaskStatusRequest.SerializeToString,
            computation__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
